require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-lint/tasks/puppet-lint'
<% if @configs['requirements']
     @configs['requirements'].each do |r| -%>
require '<%= r %>'
<%   end
   end -%>

Rake::Task[:lint].clear
PuppetLint.configuration.fail_on_warnings
<% checks = @configs['default_disabled_lint_checks'] + ( @configs['extra_disabled_lint_checks'] || [] ) -%>
<% checks.each do |check| -%>
PuppetLint.configuration.send('<%= check %>')
<% end -%>
PuppetLint.configuration.ignore_paths = ["spec/**/*.pp", "pkg/**/*.pp", "vendor/**/*.pp"]

PuppetSyntax.exclude_paths = ["spec/fixtures/**/*.pp", "vendor/**/*"]

desc "Lint metadata.json file"
task :metadata do
  sh "metadata-json-lint metadata.json<%= @configs['metadata-json-lint_options'].map { |r| ' --' + r }.join() if @configs['metadata-json-lint_options'] %>"
end
